### ISSUE TITLE
Cannot find KochavaTrackerDelegate in scope

### ISSUE THREAD

**Issue by kylebrowning** [Kochava/Apple-SwiftPackage-KochavaCore#2]
I am importing `KochavaCore` and have included KochavaCore as a dependency on my target, however I get the following error

![image](https://user-images.githubusercontent.com/113023/92755799-0b865c00-f341-11ea-9359-17b1c9e2a85b.png)

Have names changed? I couldn't find anything new.

**Comment by kylebrowning** [comment]
I tried following these instructions, https://support.kochava.com/sdk-integration/ios-sdk-integration/

But there is no such module KochavaTracker

**Comment by kylebrowning** [comment]
I got it, have to include https://github.com/Kochava/Apple-SwiftPackage-KochavaTracker not core. thanks.

**Comment by johnbushnell** [comment]
You'll still need core in your project.  Also be advised that protocol KochavaTrackerDelegate was removed and replaced with a method to get the attribution result with a completion handler.  See section "Retrieving Attribution" down on this page [here](https://support.kochava.com/sdk-integration/ios-sdk-integration/ios-using-the-sdk/).

**Comment by kylebrowning** [comment]
@johnbushnell thanks for the update. Ive successfully migrated!

Curious why SPM doesn't pull in Core tho as a dep.

**Comment by johnbushnell** [comment]
We're trying to work through that ourselves.  We've attempted to do that with the package file's definition, but it's not working.  It appears we need a dependencies feature on the .binaryTarget support which does not currently exist like it does on .target.

**Comment by kylebrowning** [comment]
@johnbushnell Interesting, good luck. This works for now!
